trigger:
- main # Trigger pipeline on changes to the 'main' branch (update as needed)

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'Maxten-01' # Replace with your Docker image name
  dockerImageTag: '$(Build.BuildId)' # Use the Build ID as the tag (or replace with your preferred tag)

stages:
- stage: BuildAndPushDockerImage
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    steps:
    - task: Checkout@1
      displayName: Checkout code

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
#        repository: $(dockerImageName)
        repository: DemoRegistry132
        dockerfile: '$(Build.SourcesDirectory)/Maxant-9090/Dockerfile' # Adjust if your Dockerfile is in a subdirectory
        containerRegistry: 'Anoop-Custom-Service'
        tags: |
          $(dockerImageTag)
